# Generated by Django 6.0 on 2025-12-22 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kecamatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=200, verbose_name='Nama Lokasi')),
                ('youtube_video_id', models.CharField(help_text='ID video dari URL YouTube (contoh: dQw4w9WgXcQ)', max_length=50, verbose_name='YouTube Video ID')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Koordinat latitude lokasi CCTV', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Koordinat longitude lokasi CCTV', max_digits=10, verbose_name='Longitude')),
                ('is_active', models.BooleanField(choices=[(True, 'Aktif'), (False, 'Tidak Aktif')], default=True, verbose_name='Status')),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi tambahan lokasi CCTV (opsional)', null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cctv_list', to='dashboard.kecamatan', verbose_name='Kecamatan')),
            ],
            options={
                'verbose_name': 'CCTV',
                'verbose_name_plural': 'CCTV',
                'ordering': ['kecamatan', 'nama_lokasi'],
            },
        ),
    ]
