# Generated by Django 6.0 on 2025-12-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctv',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Koordinat latitude lokasi CCTV (opsional)', max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cctv',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Koordinat longitude lokasi CCTV (opsional)', max_digits=10, null=True, verbose_name='Longitude'),
        ),
    ]
