# Generated by Django 6.0 on 2026-01-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_cctv_latitude_alter_cctv_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctv',
            name='last_status_check',
            field=models.DateTimeField(blank=True, help_text='Waktu terakhir status video dicek', null=True, verbose_name='Terakhir Dicek'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='status_check_error',
            field=models.TextField(blank=True, help_text='Pesan error jika pengecekan status gagal', null=True, verbose_name='Error Pengecekan'),
        ),
    ]
