# Generated by Django 5.2 on 2026-02-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_cctv_last_status_check_cctv_status_check_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctv',
            name='search_keyword',
            field=models.CharField(blank=True, help_text='Kata kunci unik di judul video YouTube untuk mencocokkan lokasi ini (misal: "Gajah Mada")', max_length=100, null=True, verbose_name='Kata Kunci Pencarian'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='ID Channel yang menyiarkan CCTV ini (opsional, untuk auto-discovery)', max_length=100, null=True, verbose_name='YouTube Channel ID'),
        ),
        migrations.AlterField(
            model_name='cctv',
            name='youtube_video_id',
            field=models.CharField(help_text='ID video dari URL YouTube (contoh: dQw4w9WgXcQ). Akan diupdate otomatis jika Channel ID dan Keyword diisi.', max_length=50, verbose_name='YouTube Video ID'),
        ),
    ]
