# Generated by Django 5.2 on 2026-02-23 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_cctv_search_keyword_cctv_youtube_channel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Channel')),
                ('channel_id', models.CharField(help_text='ID unik Channel YouTube (contoh: UCxxxxx)', max_length=100, unique=True, verbose_name='YouTube Channel ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
            ],
            options={
                'verbose_name': 'YouTube Channel',
                'verbose_name_plural': 'YouTube Channel',
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='cctv',
            name='youtube_channel_id',
        ),
        migrations.AlterField(
            model_name='cctv',
            name='youtube_video_id',
            field=models.CharField(help_text='ID video dari URL YouTube (contoh: dQw4w9WgXcQ). Akan diupdate otomatis jika Channel dan Keyword diisi.', max_length=50, verbose_name='YouTube Video ID'),
        ),
        migrations.AddField(
            model_name='cctv',
            name='youtube_channel',
            field=models.ForeignKey(blank=True, help_text='Channel yang menyiarkan CCTV ini (opsional, untuk auto-discovery)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cctv_list', to='dashboard.youtubechannel', verbose_name='YouTube Channel'),
        ),
    ]
